### PR TITLE
Set up algo_trading CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by Coulbe**
Algorithmic trading [skip ci]

### CODE REVIEW

**Comment by Coulbe** [comment]
algo_traders@azure-pipelines in working progress

**Comment by Coulbe** [comment]
algo_traders@azure-pipelines in working progress

**Review by Coulbe — COMMENTED** [review]
This commit is an attempt to build a continuous integrated (CI) algorithmic trading environment with Azure Pipelines -  using the dockerfile in chapter 2.

**Comment by yhilpisch** [comment]
I am not accepting any pull requests for this repository.

**Pull request closed without merging**
